name: Build And Push Images To Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 3'

jobs:
  stardew-multiplayer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: |-
              linux/amd64
          context: "{{defaultContext}}:docker"
          push: true
          tags: bluecobblestone/stardew-multiplayer-docker:latest
